#!/usr/bin/env bash
# Regenerate the single file uploaded to project knowledge.
# Concatenates the live-state files (and docs/ if present) into PROJECT-CONTEXT.md.
# The monolith is NOT included — it is read-only reference, not live state.
set -euo pipefail
cd "$(dirname "$0")"

OUT="PROJECT-CONTEXT.md"
BILLY_CSV="docs/BILLY-TASKS.csv"
BILLY_URL="https://docs.google.com/spreadsheets/d/e/2PACX-1vQ2NfxnnefJR_a2mHpfIU0dDQZam_xp-qEStqVhY8QL0Nux0RMFQobDWVHCociiWgYbXLgzQI_up-Oh/pub?output=csv"

# Pull Billy's task sheet fresh on every run. Deliberately NON-FATAL: this
# script runs with `set -e`, and a flaky network or a Google outage must not
# stop PROJECT-CONTEXT.md regenerating. On failure the previously fetched
# copy is kept and a warning is printed.
mkdir -p docs
if curl -sSL --max-time 30 --fail -o "$BILLY_CSV.tmp" "$BILLY_URL" 2>/dev/null \
   && [ -s "$BILLY_CSV.tmp" ]; then
  mv "$BILLY_CSV.tmp" "$BILLY_CSV"
  echo "Fetched Billy's task sheet -> $BILLY_CSV ($(wc -l < "$BILLY_CSV" | tr -d ' ') lines)."
else
  rm -f "$BILLY_CSV.tmp"
  if [ -f "$BILLY_CSV" ]; then
    echo "WARNING: could not fetch Billy's task sheet; keeping the existing $BILLY_CSV."
  else
    echo "WARNING: could not fetch Billy's task sheet and no local copy exists."
  fi
fi

{
  echo "# Gazelle Books — Project Context"
  echo "_Generated $(date '+%Y-%m-%d %H:%M') by build-context.sh. Do not edit this file directly — edit STATUS.md / DONE.md / CLAUDE.md and re-run._"
  echo
  echo "---"
  echo
  cat CLAUDE.md
  echo
  echo "---"
  echo
  cat STATUS.md
  echo
  echo "---"
  echo
  # docs/ detail files, if the carve has happened
  if [ -d docs ]; then
    for f in docs/*.md; do
      [ -e "$f" ] || continue
      cat "$f"; echo; echo "---"; echo
    done
  fi
  # Billy's task sheet, verbatim. Rows are matched by the Page column and
  # columns D/E are his and Grant's status columns - never reorder rows.
  if [ -f "$BILLY_CSV" ]; then
    echo "# Billy's task sheet (docs/BILLY-TASKS.csv)"
    echo
    echo "_Fetched from the published Google Sheet by build-context.sh. Columns D/E are"
    echo "status columns (D = Billy, E = Grant Notes). Rows are matched by the **Page**"
    echo "column - do NOT reorder rows._"
    echo
    echo '```csv'
    cat "$BILLY_CSV"
    echo '```'
    echo
    echo "---"
    echo
  fi

  cat DONE.md
} > "$OUT"

echo "Wrote $OUT ($(wc -l < "$OUT") lines)."
echo "Next: drag $OUT into project knowledge."
