#!/usr/bin/env bash
# Regenerate the single file uploaded to project knowledge.
# Concatenates the live-state files (and docs/ if present) into PROJECT-CONTEXT.md.
# The monolith is NOT included — it is read-only reference, not live state.
set -euo pipefail
cd "$(dirname "$0")"

OUT="PROJECT-CONTEXT.md"

{
  echo "# Gazelle Books — Project Context"
  echo "_Generated $(date '+%Y-%m-%d %H:%M') by build-context.sh. Do not edit this file directly — edit STATUS.md / DONE.md / CLAUDE.md and re-run._"
  echo
  echo "---"
  echo
  cat CLAUDE.md
  echo
  echo "---"
  echo
  cat STATUS.md
  echo
  echo "---"
  echo
  # docs/ detail files, if the carve has happened
  if [ -d docs ]; then
    for f in docs/*.md; do
      [ -e "$f" ] || continue
      cat "$f"; echo; echo "---"; echo
    done
  fi
  cat DONE.md
} > "$OUT"

echo "Wrote $OUT ($(wc -l < "$OUT") lines)."
echo "Next: drag $OUT into project knowledge."
